version: '3.8'
services:
  backend:
    image: grunby/adgo:uwsgi
    restart: always
    volumes:
      - logs-vol:/app/log
      - static-files-vol:/app/static
      - ${PWD}/credentials.json:/app/credentials.json
    env_file:
      - env
    expose:
      - "3000"

  frontend:
    image: nginx
    restart: always
    volumes:
      - ./deploy/nginx-compose.conf:/etc/nginx/conf.d/default.conf:ro
      - static-files-vol:/usr/share/nginx/html/:ro
    depends_on:
      - backend
    ports:
      - 80:80

volumes:
  logs-vol:
  static-files-vol:
