---
apiVersion: v1
kind: Secret
metadata:
  name: adgo-secret
  namespace: {{ .Values.namespace }}
  labels:
      app: adgo
type: Opaque
data:
  OKTA_API_TOKEN:  {{ .Values.secret.OKTA_API_TOKEN }}
  OKTA_USER_PASS:  {{ .Values.secret.OKTA_USER_PASS }}
  GMAIL_USER_PASS:  {{ .Values.secret.GMAIL_USER_PASS }}
  AD_ADMIN_PASS:  {{ .Values.secret.AD_ADMIN_PASS }}
  AD_ADMIN_USER:  {{ .Values.secret.AD_ADMIN_USER }}
  AD_USER_PASS:  {{ .Values.secret.AD_USER_PASS }}

