---
apiVersion: v1
kind: Service
metadata:
  name: adgo-service
  namespace: {{ .Values.namespace }}
  labels:
    app: adgo
spec:
  selector:
    app: adgo
  type: ClusterIP
  ports:
    - name: adgo-uwsgi
      protocol: TCP
      port: 80

